# Generated by Django 2.2.28 on 2023-04-21 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('datatime', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('image', models.CharField(max_length=256)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AttendEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendevent_event', to='home.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendevent_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
